name = "Laura Humphries"
description = "Birmingham based artist. Acrylic animal and pet paintings."
keywords = "Lauraeve, lauraeve_art, instagram, LauraEveArt, etsy, @lauraeveart, tiktok, art, handpainted, custom, acrylic, pet, animal, painting, artist, birmingham"
image = "laura.webp"
theme = "light"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-QXLBNBP2EW"
base_url = "https://www.instagram.com/lauraeve_art/"

[[sections]]
title = "Works For Sale"
description = "Here are my current pieces that are up for sale, please get in touch if any of them catch your eye"
direction = "column"
item_style = "outline"
[[sections.items]]
icon = "for_sale1.jpg"
[[sections.items]]
icon = "for_sale2.jpg"
[[sections.items]]
icon = "for_sale3.jpg"
[[sections.items]]
icon = "for_sale4.jpg"
[[sections.items]]
icon = "for_sale5.jpg"


[[sections]]
title = "Links"
description = "Look for me here!"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "lauraeve_art"
url = "https://www.instagram.com/lauraeve_art/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/etsy/ffffff"
title = "LauraEveArt"
url = "https://www.etsy.com/uk/shop/LauraEveArt/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/tiktok/ffffff"
title = "@lauraeveart"
url = "https://www.tiktok.com/@lauraeveart/"
