name = "Laura Humphries"
description = "Birmingham based artist. Acrylic animal and pet paintings."
keywords = "Lauraeve, art, etsy, handpainted, custom"
image = "laura.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://www.instagram.com/lauraeve_art/"

[[sections]]
title = "Links"
description = "Look for me here!"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/lauraeve_art/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/etsy/ffffff"
title = "Etsy"
url = "https://www.etsy.com/uk/shop/LauraEveArt/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/tiktok/ffffff"
title = "TikTok"
url = "https://www.tiktok.com/@lauraeveart/"
